// import laptop from "../src/assets/images/products/1.png";
// At the top of data.js
const images = import.meta.glob(
  "./assets/images/products/*.{png,jpg,jpeg,webp}",
  {
    eager: true,
    import: "default",
  }
);

const getImage = (imageName) => {
  const imagePath = `./assets/images/products/${imageName}`;
  return images[imagePath];
};

// data.js

export const features = [
  {
    id: 1,
    iconClass: "bi bi-truck",
    title: "Free Delivery",
    description: "Orders from all items",
  },
  {
    id: 2,
    iconClass: "bi bi-coin",
    title: "Return & Refund",
    description: "Money back guarantee",
  },
  {
    id: 3,
    iconClass: "bi bi-gear",
    title: "Member Discount",
    description: "On order over $99",
  },
  {
    id: 4,
    iconClass: "bi bi-headset",
    title: "Support 24/7",
    description: "Contact us 24 hours a day",
  },
];

export const products = [
  // Beauty Products
  {
    id: 1,
    category: "beauty",
    title: "Essence Mascara Lash Princess",
    price: 9.27,
    oldPrice: 9.99,
    discount: "-7.17%",
    rating: 4.94,
    image: getImage("1.png"),
    qty: 1,
  },
  {
    id: 2,
    category: "beauty",
    title: "Eyeshadow Palette with Mirror",
    price: 18.89,
    oldPrice: 19.99,
    discount: "-5.5%",
    rating: 3.28,
    image: getImage("2.png"),
    qty: 1,
  },
  {
    id: 3,
    category: "beauty",
    title: "Powder Canister",
    price: 12.27,
    oldPrice: 14.99,
    discount: "-18.14%",
    rating: 3.82,
    image: getImage("3.png"),
    qty: 1,
  },
  {
    id: 4,
    category: "beauty",
    title: "Red Lipstick",
    price: 10.52,
    oldPrice: 12.99,
    discount: "-19.03%",
    rating: 2.51,
    image: getImage("4.png"),
    qty: 1,
  },
  {
    id: 5,
    category: "beauty",
    title: "Compact Powder Kit",
    price: 8.99,
    oldPrice: 10.99,
    discount: "-18.2%",
    rating: 4.21,
    image: getImage("5.png"),
    qty: 1,
  },

  // Fragrances
  {
    id: 6,
    category: "fragrance",
    title: "Men's Eau de Toilette",
    price: 22.99,
    oldPrice: 25.99,
    discount: "-11.54%",
    rating: 4.2,
    image: getImage("6.jpg"),
    qty: 1,
  },
  {
    id: 7,
    category: "fragrance",
    title: "Women's Body Mist",
    price: 13.99,
    oldPrice: 15.99,
    discount: "-12.5%",
    rating: 3.8,
    image: getImage("7.webp"),
    qty: 1,
  },
  {
    id: 8,
    category: "fragrance",
    title: "Luxury Perfume Spray",
    price: 44.5,
    oldPrice: 49.99,
    discount: "-11%",
    rating: 4.7,
    image: getImage("8.jpg"),
    qty: 1,
  },
  {
    id: 9,
    category: "fragrance",
    title: "Fresh Citrus Cologne",
    price: 19.75,
    oldPrice: 22.5,
    discount: "-12.22%",
    rating: 4.0,
    image: getImage("8.jpg"),
    qty: 1,
  },
  {
    id: 10,
    category: "fragrance",
    title: "Night Oud Perfume",
    price: 39.99,
    oldPrice: 45.0,
    discount: "-11.13%",
    rating: 4.3,
    image: getImage("9.webp"),
    qty: 1,
  },

  // Groceries
  {
    id: 11,
    category: "groceries",
    title: "Organic Brown Rice - 1kg",
    price: 3.99,
    oldPrice: 4.99,
    discount: "-20%",
    rating: 4.2,
    image: getImage("11.webp"),
    qty: 1,
  },
  {
    id: 12,
    category: "groceries",
    title: "Olive Oil Extra Virgin - 500ml",
    price: 6.99,
    oldPrice: 8.5,
    discount: "-17.76%",
    rating: 4.5,
    image: getImage("12.webp"),
    qty: 1,
  },
  {
    id: 13,
    category: "groceries",
    title: "All-Purpose Flour - 2kg",
    price: 2.5,
    oldPrice: 2.99,
    discount: "-16.72%",
    rating: 4.1,
    image: getImage("13.webp"),
    qty: 1,
  },
  {
    id: 14,
    category: "groceries",
    title: "Canned Chickpeas - Pack of 3",
    price: 2.99,
    oldPrice: 3.49,
    discount: "-14.33%",
    rating: 3.9,
    image: getImage("14.webp"),
    qty: 1,
  },
  {
    id: 15,
    category: "groceries",
    title: "Instant Noodles - 5 Pack",
    price: 3.25,
    oldPrice: 3.75,
    discount: "-13.33%",
    rating: 4.6,
    image: getImage("15.webp"),
    qty: 1,
  },

  // Decoration
  {
    id: 16,
    category: "decoration",
    title: "LED Fairy String Lights",
    price: 14.99,
    oldPrice: 18.99,
    discount: "-21.06%",
    rating: 4.63,
    image: getImage("16.webp"),
    qty: 1,
  },
  {
    id: 17,
    category: "decoration",
    title: "Ceramic Flower Vase",
    price: 22.49,
    oldPrice: 25.99,
    discount: "-13.47%",
    rating: 4.78,
    image: getImage("17.png"),
    qty: 1,
  },
  {
    id: 18,
    category: "decoration",
    title: "Wall Hanging Macrame",
    price: 16.75,
    oldPrice: 20.0,
    discount: "-16.25%",
    rating: 4.52,
    image: getImage("18.webp"),
    qty: 1,
  },
  {
    id: 19,
    category: "decoration",
    title: "Minimalist Clock Decor",
    price: 19.95,
    oldPrice: 23.5,
    discount: "-15.11%",
    rating: 4.39,
    image: getImage("19.webp"),
    qty: 1,
  },
  {
    id: 20,
    category: "decoration",
    title: "Scented Candle Set",
    price: 12.99,
    oldPrice: 16.99,
    discount: "-23.54%",
    rating: 4.66,
    image: getImage("20.png"),
    qty: 1,
  },
];
